# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Testopia
tagline:          'The ultimate testing blog...'
description:      'This is a software testing blog from two quality engineers with more than 6 years of industry experience. <a href="#" target="_blank">Akshay Jain / Dhawal Sarwate</a> Theme of this blog is made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Akshay Jain'
  url:            https://plus.google.com/akshay059

paginate:         5


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/akshay059
